In [1]:
import tensorflow as tf
import numpy as np

In [10]:
def dice_coefficient(label, infer):
    
    label_flatten = tf.layers.flatten(label)
    infer_flatten = tf.layers.flatten(infer)
    TP = tf.reduce_sum(tf.cast(tf.equal(label_flatten,infer_flatten), dtype=tf.float32))
    FN = tf.reduce_sum(tf.cast(tf.equal(label_flatten,(1-infer_flatten)), dtype=tf.float32))
    FP = tf.reduce_sum(tf.cast(tf.equal((1-label_flatten),infer_flatten), dtype=tf.float32))
    
    bottom = FN+FP+(2*TP)
    up = 2*TP
    return up/bottom

In [3]:
a = tf.constant(np.random.randint(0,3,[5,5])*0.5)
b = tf.constant(np.random.randint(0,3,[5,5])*0.5)

In [4]:
sess = tf.Session()

In [5]:
print(sess.run(a))


[[ 0.5  0.5  0.5  0.5  0.5]
 [ 0.5  0.   0.5  0.   1. ]
 [ 0.5  0.   1.   0.5  1. ]
 [ 0.   0.   0.5  1.   0.5]
 [ 0.5  0.   0.5  0.5  1. ]]


In [6]:
print(sess.run(tf.round(a)))


[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.]
 [ 0.  0.  1.  0.  1.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]


In [7]:
print(sess.run(b))

[[ 1.   0.   0.   1.   0.5]
 [ 0.   1.   1.   1.   0. ]
 [ 0.   0.5  1.   0.5  0. ]
 [ 0.   0.5  0.   0.   1. ]
 [ 0.5  1.   0.   0.   0. ]]


In [11]:
sess.run(dice_coefficient(a,b))

0.33333334